
module.exports = {
    characters: [
        {
            char_id: 1,
            name: 'Walter White',
            nickname: 'Heisenberg',
            birthday: '1958-09-07',
            status: 'Presumed dead',
            occupation: ['High School Chemistry Teacher', 'Meth King Pin'],
            img: 'https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_walter-white-lg.jpg',
            portrayed: 'Bryan Cranston',
            category: ['Breaking Bad']
        },
        {
            char_id: 2,
            name: 'Jesse Pinkman',
            nickname: "Cap n' Cook",
            birthday: '1984-09-24',
            status: 'Alive',
            occupation: ['Meth Dealer'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/9/95/JesseS5.jpg/revision/latest?cb=20120620012441',
            portrayed: 'Aaron Paul',
            category: ['Breaking Bad']
        },
        {
            char_id: 3,
            name: 'Skyler White',
            nickname: 'Sky',
            birthday: '1970-08-11',
            status: 'Alive',
            occupation: [
                'House wife',
                'Book Keeper',
                'Car Wash Manager',
                'Taxi Dispatcher'
            ],
            img: 'https://s-i.huffpost.com/gen/1317262/images/o-ANNA-GUNN-facebook.jpg',
            portrayed: 'Anna Gunn',
            category: ['Breaking Bad']
        },
        {
            char_id: 4,
            name: 'Walter White Jr.',
            nickname: 'Flynn',
            birthday: '1993-07-08',
            status: 'Alive',
            occupation: ['Teenager'],
            img: 'https://media1.popsugar-assets.com/files/thumbor/WeLUSvbAMS_GL4iELYAUzu7Bpv0/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2018/01/12/910/n/1922283/fb758e62b5daf3c9_TCDBRBA_EC011/i/RJ-Mitte-Walter-White-Jr.jpg',
            portrayed: 'RJ Mitte',
            category: ['Breaking Bad']
        },
        {
            char_id: 5,
            name: 'Henry Schrader',
            nickname: 'Hank',
            birthday: null,
            status: 'Deceased',
            occupation: ['DEA Agent'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/b/b7/HankS5.jpg/revision/latest/scale-to-width-down/700?cb=20120620014136',
            portrayed: 'Dean Norris',
            category: ['Breaking Bad']
        },
        {
            char_id: 6,
            name: 'Marie Schrader',
            nickname: 'Marie',
            birthday: null,
            status: 'Alive',
            occupation: ['Housewife', 'Clepto'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/1/10/Season_2_-_Marie.jpg/revision/latest?cb=20120617211645',
            portrayed: 'Betsy Brandt',
            category: ['Breaking Bad']
        },
        {
            char_id: 7,
            name: 'Mike Ehrmantraut',
            nickname: 'Mike',
            birthday: null,
            status: 'Deceased',
            occupation: ['Hitman', 'Private Investigator', 'Ex-Cop'],
            img: 'https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_mike-ehrmantraut-lg.jpg',
            portrayed: 'Jonathan Banks',
            category: ['Breaking Bad', 'Better Call Saul']
        },
        {
            char_id: 8,
            name: 'Saul Goodman',
            nickname: 'Jimmy McGill',
            birthday: null,
            status: 'Alive',
            occupation: ['Lawyer'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/1/16/Saul_Goodman.jpg/revision/latest?cb=20120704065846',
            portrayed: 'Bob Odenkirk',
            category: ['Breaking Bad', 'Better Call Saul']
        },
        {
            char_id: 9,
            name: 'Gustavo Fring',
            nickname: 'Gus',
            birthday: null,
            status: 'Deceased',
            occupation: ['Los-Pollos co-Founder', 'Philanthropist', 'Cartel Leader'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/1/1f/BCS_S4_Gustavo_Fring.jpg/revision/latest?cb=20180824195925',
            portrayed: 'Giancarlo Esposito',
            category: ['Breaking Bad', 'Better Call Saul']
        },
        {
            char_id: 10,
            name: 'Hector Salamanca',
            nickname: 'Don Hector',
            birthday: null,
            status: 'Deceased',
            occupation: ['Former Senior Cartel Leader'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/b/b4/Hector_BCS.jpg/revision/latest?cb=20170810091606',
            portrayed: 'Mark Margolis',
            category: ['Breaking Bad', 'Better Call Saul']
        },
        {
            char_id: 11,
            name: 'Domingo Molina',
            nickname: 'Krazy-8',
            birthday: null,
            status: 'Deceased',
            occupation: ['Meth Distributor'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/e/e7/Krazy8.png/revision/latest?cb=20130208041554',
            portrayed: 'Maximino Arciniega',
            category: ['Breaking Bad']
        },
        {
            char_id: 12,
            name: 'Tuco Salamanca',
            nickname: 'Tuco',
            birthday: null,
            status: 'Deceased',
            occupation: ['Meth Distributor'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/a/a7/Tuco_BCS.jpg/revision/latest?cb=20170810082445',
            portrayed: 'Raymond Cruz',
            category: ['Breaking Bad', 'Better Call Saul']
        },
        {
            char_id: 13,
            name: 'Marco & Leonel Salamanca',
            nickname: 'The Cousins',
            birthday: null,
            status: 'Deceased',
            occupation: ['Cartel Hitman'],
            img: 'https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_the-cousins-lg.jpg',
            portrayed: 'Luis & Daniel Moncada',
            category: ['Breaking Bad']
        },
        {
            char_id: 14,
            name: 'Lydia Rodarte-Quayle',
            nickname: 'Lydia',
            birthday: null,
            status: 'Deceased',
            occupation: ['Executive at Madrigal'],
            img: 'https://media1.popsugar-assets.com/files/thumbor/wERDST0TUb-iHCSb2r5ZpsvaZLo/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2013/07/17/675/n/1922283/fae2f583f04bb80f_Laura-Fraser-is-back-as-Lydia-Rodarte-Quayle_gallery_primary/i/Laura-Fraser-Lydia-Rodarte-Quayle.jpg',
            portrayed: 'Laura Fraser',
            category: ['Breaking Bad']
        },
        {
            char_id: 15,
            name: 'Todd Alquist',
            nickname: 'Ricky Hitler',
            birthday: null,
            status: 'Deceased',
            occupation: ['Lab Assistant', 'Enforcer', 'Meth Cook'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/9/95/Todd_brba5b.png/revision/latest?cb=20130717134303',
            portrayed: 'Jesse Plemons',
            category: ['Breaking Bad']
        },
        {
            char_id: 16,
            name: 'Jane Margolis',
            nickname: 'Apology Girl',
            birthday: null,
            status: 'Deceased',
            occupation: ['Tattoo Artist', 'Landlord'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/b/b4/Jane.jpg/revision/latest?cb=20090621233653',
            portrayed: 'Krysten Ritter',
            category: ['Breaking Bad']
        },
        {
            char_id: 17,
            name: 'Skinny Pete',
            nickname: 'Skinny',
            birthday: null,
            status: 'Alive',
            occupation: ['Low-level meth distributer'],
            img: 'https://vignette.wikia.nocookie.net/breaking-bad-tv/images/c/ce/Sp.png/revision/latest?cb=20121016143623',
            portrayed: 'Charles Baker',
            category: ['Breaking Bad']
        },
        {
            char_id: 18,
            name: 'Brandon Mayhew',
            nickname: 'Badger',
            birthday: null,
            status: 'Alive',
            occupation: ['Low-level meth distributer'],
            img: 'https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_badger-lg.jpg',
            portrayed: 'Matt L. Jones',
            category: ['Breaking Bad']
        },
        {
            char_id: 19,
            name: 'Huell Babineaux',
            nickname: 'Huell',
            birthday: null,
            status: 'Alive',
            occupation: ['Bodyguard'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/c/c1/4x11_-_Huell.png/revision/latest?cb=20130913100459&path-prefix=es',
            portrayed: 'Lavell Crawford',
            category: ['Breaking Bad']
        },
        {
            char_id: 20,
            name: 'Steven Gomez',
            nickname: 'Gomie',
            birthday: null,
            status: 'Deceased',
            occupation: ['DEA Agent'],
            img: 'https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_steven-gomez-lg.jpg',
            portrayed: 'Steven Michael Quezada',
            category: ['Breaking Bad']
        },
        {
            char_id: 21,
            name: 'Theodore Beneke',
            nickname: 'Ted',
            birthday: null,
            status: 'Alive',
            occupation: ['Former President Beneke Fabricators'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/b/bd/Cast_bb_700x1000_todd-beneke-lg.jpg/revision/latest?cb=20170723165057',
            portrayed: 'Christopher Cousins',
            category: ['Breaking Bad']
        },
        {
            char_id: 22,
            name: 'Gale Boetticher',
            nickname: 'GB',
            birthday: null,
            status: 'Deceased',
            occupation: ['Chemist', 'Meth manufacturer'],
            img: 'https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_gale-boetticher-lg.jpg',
            portrayed: 'David Costabile',
            category: ['Breaking Bad']
        },
        {
            char_id: 23,
            name: 'Andrea Cantillo',
            nickname: 'Andrea',
            birthday: null,
            status: 'Deceased',
            occupation: ['Unknown'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/5/51/Andrea_-_To%27hajilee.png/revision/latest?cb=20131025094457',
            portrayed: 'Emily Rios',
            category: ['Breaking Bad']
        },
        {
            char_id: 24,
            name: 'Brock Cantillo',
            nickname: 'Brock',
            birthday: null,
            status: 'Alive',
            occupation: ['Kid'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/9/97/Brock.png/revision/latest?cb=20170725193144',
            portrayed: 'Ian Posada',
            category: ['Breaking Bad']
        },
        {
            char_id: 25,
            name: 'Carmen Molina',
            nickname: 'Carmen',
            birthday: null,
            status: 'Alive',
            occupation: ['High School Principal'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/d/de/Carmen.JPG/revision/latest?cb=20100410125233',
            portrayed: 'Carmen Serano',
            category: ['Breaking Bad']
        },
        {
            char_id: 26,
            name: 'Gretchen Schwartz',
            nickname: 'Gretchen',
            birthday: null,
            status: 'Alive',
            occupation: ['Co-owner Gray Matter'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/5/5e/Gretchen_Schwartz.png/revision/latest?cb=20131005103735&path-prefix=es',
            portrayed: 'Jessica Hecht',
            category: ['Breaking Bad']
        },
        {
            char_id: 27,
            name: 'Elliot Schwartz',
            nickname: 'Elliot',
            birthday: null,
            status: 'Alive',
            occupation: ['Co-Founder Gray Matter'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/8/8a/Elliott_Schwartz.png/revision/latest?cb=20131005103743&path-prefix=es',
            portrayed: 'Adam Godley',
            category: ['Breaking Bad']
        },
        {
            char_id: 28,
            name: 'Gonzo',
            nickname: 'Gonzo',
            birthday: null,
            status: 'Deceased',
            occupation: ["Tuco's Bodyguard"],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/d/d6/Gonzo.JPG/revision/latest?cb=20100415212944',
            portrayed: 'Jesus, Payan, Jr.',
            category: ['Breaking Bad']
        },
        {
            char_id: 29,
            name: 'Christian Ortgea',
            nickname: 'Combo',
            birthday: null,
            status: 'Deceased',
            occupation: ['Low-level meth distributor'],
            img: 'https://res.cloudinary.com/dwvrok1le/image/upload/v1540314304/c8acek3pimb0hb4efrvf.jpg',
            portrayed: 'Rodney Rush',
            category: ['Breaking Bad']
        },
        {
            char_id: 30,
            name: 'Mrs. Pinkman',
            nickname: "Jesse's mom",
            birthday: null,
            status: 'Alive',
            occupation: ['unknown'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/a/a2/Tess_Harper.jpg/revision/latest?cb=20120923235754',
            portrayed: 'Tess Harper',
            category: ['Breaking Bad']
        },
        {
            char_id: 31,
            name: 'Adam Pinkman',
            nickname: "Jesse's dad",
            birthday: null,
            status: 'Alive',
            occupation: ['unknown'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/c/c9/AdamPinkman.png/revision/latest?cb=20141117180836&path-prefix=es',
            portrayed: 'Michael Bofshever',
            category: ['Breaking Bad']
        },
        {
            char_id: 32,
            name: 'Jake Pinkman',
            nickname: 'Jake',
            birthday: null,
            status: 'Alive',
            occupation: ['Kid', "Jesse's little brother"],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/a/a4/Jake.jpg/revision/latest?cb=20121214201656&path-prefix=de',
            portrayed: 'Ben Petry',
            category: ['Breaking Bad']
        },
        {
            char_id: 33,
            name: 'No-Doze',
            nickname: 'No-Doze',
            birthday: null,
            status: 'Deceased',
            occupation: ['Juarez Cartel Lieutenant'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/c/ca/No_Doze_2.png/revision/latest?cb=20131014073210',
            portrayed: 'Cesar Garcia',
            category: ['Breaking Bad']
        },
        {
            char_id: 34,
            name: 'Emilio Koyama',
            nickname: 'Emilio',
            birthday: null,
            status: 'Deceased',
            occupation: ['Low-level meth distributor'],
            img: 'https://vignette.wikia.nocookie.net/trbreakingbad/images/9/9c/Emilio.jpeg/revision/latest?cb=20161029192022',
            portrayed: 'John Koyama',
            category: ['Breaking Bad']
        },
        {
            char_id: 35,
            name: 'Dr. Delcavoli',
            nickname: 'Dr. Delcavoli',
            birthday: null,
            status: 'Alive',
            occupation: ['Physician'],
            img: 'https://res.cloudinary.com/dwvrok1le/image/upload/v1540314509/lj5qlbe6xvmmpxnspz6y.jpg',
            portrayed: 'David House',
            category: ['Breaking Bad']
        },
        {
            char_id: 36,
            name: 'Wendy S.',
            nickname: 'Wendy',
            birthday: null,
            status: 'Alive',
            occupation: ['Prostitute'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/c/cc/Wendy.jpg/revision/latest?cb=20170721162715',
            portrayed: 'Julie Minesci',
            category: ['Breaking Bad']
        },
        {
            char_id: 37,
            name: 'Bogdan Wolynetz',
            nickname: 'Bogdan',
            birthday: null,
            status: 'Alive',
            occupation: ['Former owner of A1A Car Wash'],
            img: 'https://i.pinimg.com/originals/d5/c0/34/d5c0345ae70fbdbaa33b7537d685da54.jpg',
            portrayed: 'Marius Stan',
            category: ['Breaking Bad']
        },
        {
            char_id: 38,
            name: 'Ken',
            nickname: 'Ken Wins',
            birthday: null,
            status: 'Alive',
            occupation: ['Stock Broker'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/8/8c/Ken.png/revision/latest?cb=20170721163649',
            portrayed: 'Kyle Bornheimer',
            category: ['Breaking Bad']
        },
        {
            char_id: 39,
            name: 'Holly White',
            nickname: 'Holly',
            birthday: null,
            status: 'Alive',
            occupation: ['Infant'],
            img: 'https://static.wikia.nocookie.net/breakingbad/images/0/08/Tumblr_lqddc79K9S1qc5omm.png/revision/latest?cb=20111012055605',
            portrayed: 'Unknown',
            category: ['Breaking Bad']
        },
        {
            char_id: 40,
            name: 'George Merkert',
            nickname: 'ASAC Merkert',
            birthday: null,
            status: 'Alive',
            occupation: ['Former Head of Albuquerque DEA'],
            img: 'https://m.media-amazon.com/images/M/MV5BMTkwMTkxNjUzM15BMl5BanBnXkFtZTgwMTg5MTczMTE@._V1_UY317_CR175,0,214,317_AL_.jpg',
            portrayed: 'Michael Shamus Wiles',
            category: ['Breaking Bad']
        },
        {
            char_id: 41,
            name: 'Donald Margolis',
            nickname: "Jane's dad",
            birthday: null,
            status: 'Unknown',
            occupation: ['Air-Traffic Controller', 'Landlord'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/1/12/Donald_Margolis.png/revision/latest?cb=20120802212034',
            portrayed: 'John de Lancie',
            category: ['Breaking Bad']
        },
        {
            char_id: 42,
            name: 'Clovis',
            nickname: 'Clovis',
            birthday: null,
            status: 'Alive',
            occupation: ['Mechanic'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/0/0f/Clovis.JPG/revision/latest?cb=20100415221013',
            portrayed: 'Tom Kiesche',
            category: ['Breaking Bad']
        },
        {
            char_id: 43,
            name: 'SAC Ramey',
            nickname: 'SAC Ramey',
            birthday: null,
            status: 'Alive',
            occupation: ['DEA agent'],
            img: 'https://res.cloudinary.com/dwvrok1le/image/upload/v1539360786/o7thsjdorobfbetqaefj.jpg',
            portrayed: 'Todd Terry',
            category: ['Breaking Bad']
        },
        {
            char_id: 44,
            name: 'Victor',
            nickname: 'Victor',
            birthday: null,
            status: 'Deceased',
            occupation: ['Henchman of Gustavo Fring'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/4/48/Victor2.png/revision/latest?cb=20131009225027',
            portrayed: 'Jeremiah Bitsui',
            category: ['Breaking Bad']
        },
        {
            char_id: 45,
            name: 'Tomás Cantillo',
            nickname: "Andrea's brother",
            birthday: null,
            status: 'Deceased',
            occupation: ['Kid', 'Gang member for a rival dealer in ABQ'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/e/ec/Tomas.png/revision/latest?cb=20130131043014',
            portrayed: 'Angelo Martinez',
            category: ['Breaking Bad']
        },
        {
            char_id: 46,
            name: 'Francesca Liddy',
            nickname: 'Honey Tits',
            birthday: null,
            status: 'Alive',
            occupation: [
                'Department of Motor Vehicles',
                'Secretary for Saul Goodman Associates'
            ],
            img: 'https://res.cloudinary.com/dwvrok1le/image/upload/v1539362182/o9mstjonfn6dsdi3uij6.jpg',
            portrayed: 'Tina Parker',
            category: ['Breaking Bad', 'Better Call Saul']
        },
        {
            char_id: 47,
            name: 'Cynthia',
            nickname: 'Cynthia',
            birthday: null,
            status: 'Alive',
            occupation: ['Los Pollos Hermanos Manager'],
            img: 'https://res.cloudinary.com/dwvrok1le/image/upload/v1539362375/z63youp272k5mbqbuqj9.jpg',
            portrayed: 'Ashley Kajiki',
            category: ['Breaking Bad']
        },
        {
            char_id: 48,
            name: 'Tortuga',
            nickname: 'Tortuga',
            birthday: null,
            status: 'Deceased',
            occupation: ['Juarez Cartel member', 'DEA informant'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/5/58/BBWA_Tortuga.jpg/revision/latest?cb=20131101172007',
            portrayed: 'Danny Trejo',
            category: ['Breaking Bad']
        },
        {
            char_id: 49,
            name: 'Tim Roberts',
            nickname: 'Detective Roberts',
            birthday: null,
            status: 'Alive',
            occupation: ['Detective for the APD'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/8/8d/2x02_-_Tim_Roberts.jpg/revision/latest?cb=20110927053954',
            portrayed: 'Nigel Gibbs',
            category: ['Breaking Bad']
        },
        {
            char_id: 50,
            name: 'Juan Bolsa',
            nickname: 'Don Juan',
            birthday: null,
            status: 'Deceased',
            occupation: ['Mexican drug cartel boss'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/3/38/Bolsa.png/revision/latest?cb=20180825204033',
            portrayed: 'Javier Grajeda',
            category: ['Breaking Bad']
        },
        {
            char_id: 51,
            name: 'Group Leader',
            nickname: 'Counselor',
            birthday: null,
            status: 'Alive',
            occupation: ['Drug & Alcohol Rehabilitation Counselor'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/8/81/Group_Leader_Brown_Shirt_-_Kafkaesque.png/revision/latest?cb=20131025095333',
            portrayed: 'Jere Burns',
            category: ['Breaking Bad']
        },
        {
            char_id: 52,
            name: 'Kaylee Ehrmantraut',
            nickname: "Mike's Granddaughter",
            birthday: null,
            status: 'Alive',
            occupation: ['Kid'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/c/cc/Kaylee.png/revision/latest?cb=20170810082843',
            portrayed: 'Kaija Rose Bales',
            category: ['Breaking Bad']
        },
        {
            char_id: 53,
            name: 'Pamela',
            nickname: "Skyler's attorney",
            birthday: null,
            status: 'Alive',
            occupation: ['Attorney'],
            img: 'https://res.cloudinary.com/dwvrok1le/image/upload/v1539373707/bbb6muek0tcmbc3g2sog.jpg',
            portrayed: 'Julie Dretzin',
            category: ['Breaking Bad']
        },
        {
            char_id: 54,
            name: 'Duane Chow',
            nickname: 'Chow',
            birthday: null,
            status: 'Deceased',
            occupation: ['Owner of Golden Moth Chemical'],
            img: 'https://res.cloudinary.com/dwvrok1le/image/upload/v1539373871/ssk1t4hvo9tmhvdt5hcn.jpg',
            portrayed: 'James Ning',
            category: ['Breaking Bad']
        },
        {
            char_id: 55,
            name: 'Stacey Ehrmantraut',
            nickname: "Mike's daugter-in-law",
            birthday: null,
            status: 'Alive',
            occupation: ['Mother'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/b/b3/StaceyEhrmantraut.png/revision/latest?cb=20150310150049',
            portrayed: 'Kerry Condon',
            category: ['Breaking Bad', 'Better Call Saul']
        },
        {
            char_id: 56,
            name: 'Officer Saxton',
            nickname: 'Saxton',
            birthday: null,
            status: 'Alive',
            occupation: ['APD Officer'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/f/f3/Officer_Saxton_-_I.F.T..png/revision/latest?cb=20131025090606',
            portrayed: 'Stoney Westmoreland',
            category: ['Breaking Bad']
        },
        {
            char_id: 57,
            name: 'Jack Welker',
            nickname: 'Uncle Jack',
            birthday: null,
            status: 'Deceased',
            occupation: ['Criminal Gang Leader'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/c/ce/Jack5x13.png/revision/latest?cb=20130912225922',
            portrayed: 'Michael Bowen',
            category: ['Breaking Bad']
        },
        {
            char_id: 112,
            name: 'Kimberly Wexler',
            nickname: 'Kim',
            birthday: null,
            status: 'Alive',
            occupation: ['Lawyer'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/f/f7/BCS_S4_Kim_Wexler.jpg/revision/latest?cb=20180824195845',
            portrayed: 'Rhea Seehorn',
            category: ['Better Call Saul']
        },
        {
            char_id: 113,
            name: 'Howard Hamlin',
            nickname: 'Howard',
            birthday: null,
            status: 'Alive',
            occupation: ['Lawyer'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/5/57/BCS_S4_Howard_Hamlin.jpg/revision/latest?cb=20180824195855',
            portrayed: 'Patrick Fabian',
            category: ['Better Call Saul']
        },
        {
            char_id: 114,
            name: 'Charles McGill',
            nickname: 'Chuck',
            birthday: null,
            status: 'Deceased',
            occupation: ['Lawyer'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/3/3e/BCS_S3_ChuckMcGill.jpg/revision/latest?cb=20170327185308',
            portrayed: 'Michael McKean',
            category: ['Better Call Saul']
        },
        {
            char_id: 115,
            name: 'Ignacio Varga',
            nickname: 'Nacho',
            birthday: null,
            status: 'Alive',
            occupation: ['Crimal Gang Lieutenant'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/b/b1/BCS_S4_Nacho_Varga.jpg/revision/latest?cb=20180824195910',
            portrayed: 'Michael Mano',
            category: ['Better Call Saul']
        },
        {
            char_id: 116,
            name: 'Eduardo Salamanca',
            nickname: 'Lalo',
            birthday: null,
            status: 'Alive',
            occupation: ['Cartel Member'],
            img: 'https://vignette.wikia.nocookie.net/breakingbad/images/8/85/LaloProfileBCS.png/revision/latest?cb=20180925050152',
            portrayed: 'Tony Dalton',
            category: ['Better Call Saul']
        }
    ],
    quotes: [
        {
            quote_id: 1,
            quote: 'I am not in danger, Skyler. I am the danger!',
            char_id: 1
        },
        { quote_id: 2, quote: 'Stay out of my territory.', char_id: 1 },
        { quote_id: 3, quote: 'IFT', char_id: 3 },
        {
            quote_id: 4,
            quote: 'I watched Jane die. I was there. And I watched her die. I watched her overdose and choke to death. I could have saved her. But I didn’t.',
            char_id: 1
        },
        { quote_id: 5, quote: 'Say my name.', char_id: 1 },
        {
            quote_id: 6,
            quote: 'Congratulations, you’ve just left your family a second-hand Subaru.',
            char_id: 8
        },
        {
            quote_id: 7,
            quote: 'Yeah, you do seem to have a little s*** creek action going... You know, FYI, you can buy a paddle.',
            char_id: 8
        },
        { quote_id: 8, quote: 'Tread lightly.', char_id: 1 },
        { quote_id: 9, quote: 'Funyuns are awesome.', char_id: 2 },
        { quote_id: 10, quote: 'Ooooooh, wire.', char_id: 2 },
        { quote_id: 11, quote: 'A robot?!', char_id: 2 },
        {
            quote_id: 12,
            quote: 'What good is being an outlaw when you have responsibilities.',
            char_id: 2
        },
        {
            quote_id: 13,
            quote: "You forgot your ice trays! YOU'RE GONNA NEED THE ICE TRAYS!",
            char_id: 2
        },
        {
            quote_id: 14,
            quote: 'Yeah, and thanks, Daddy Warbucks, but that was before my housing situation went completely testicular on me, okay?',
            char_id: 2
        },
        {
            quote_id: 15,
            quote: 'How am I supposed to live here now, huh? My whole house smells like toe cheese and dry cleaning.',
            char_id: 2
        },
        {
            quote_id: 16,
            quote: "I'm a blow fish! Yeah, Blow fishin' this up!",
            char_id: 2
        },
        { quote_id: 17, quote: 'Yeah, totally Kafkaesque', char_id: 2 },
        {
            quote_id: 18,
            quote: 'We make poison for people who don’t care. We probably have the most unpicky customers in the world.',
            char_id: 2
        },
        {
            quote_id: 19,
            quote: 'You don’t need a criminal lawyer. You need a criminal lawyer',
            char_id: 2
        },
        { quote_id: 20, quote: 'Oh well, heil Hitler, b****!', char_id: 2 },
        { quote_id: 21, quote: 'Yeah, science!', char_id: 2 },
        { quote_id: 22, quote: 'Yeah, b****! Magnets!', char_id: 2 },
        {
            quote_id: 23,
            quote: 'Yo 148, 3-to-the-3-to-the-6-to-the-9. Representin’ the ABQ. What up, biatch? Leave it at the tone!',
            char_id: 2
        },
        {
            quote_id: 24,
            quote: "Jesus Christ, Marie. They're minerals!",
            char_id: 5
        },
        { quote_id: 25, quote: 'My name is Skyler White, yo.', char_id: 3 },
        {
            quote_id: 26,
            quote: 'Someone has to protect this family, from the man that protects this family.',
            char_id: 3
        },
        { quote_id: 27, quote: 'Shut up! Shut up! Shut up!', char_id: 3 },
        {
            quote_id: 28,
            quote: "I'm waiting for the cancer to come back.",
            char_id: 3
        },
        {
            quote_id: 29,
            quote: "I can't remember the last time I was happy.",
            char_id: 3
        },
        { quote_id: 30, quote: "You're my free pass.... Bitch!", char_id: 2 },
        {
            quote_id: 63,
            quote: 'Chemistry is the study of matter, but I prefer to see it at the study of change.',
            char_id: 1
        },
        {
            quote_id: 64,
            quote: 'You asked me if I was in the meth business or the money business. Neither. I am in the empire business',
            char_id: 1
        },
        {
            quote_id: 65,
            quote: 'Smoking marijuana, eating cheetos, and masturbating do not constitute plans in my book.',
            char_id: 1
        },
        {
            quote_id: 66,
            quote: 'I did it for me. I liked it. I was good at it. And I was really... I was alive.',
            char_id: 1
        },
        {
            quote_id: 67,
            quote: "We're done when i say we're done.",
            char_id: 1
        },
        {
            quote_id: 68,
            quote: 'Did you not plan for this contingency? I mean, the Starship Enterprise had a self-destruct button.',
            char_id: 8
        },
        {
            quote_id: 69,
            quote: "There's no honor among thieves... Except for us of course.",
            char_id: 8
        },
        {
            quote_id: 70,
            quote: "Don't drink and drive. But if you do, call me.",
            char_id: 8
        },
        {
            quote_id: 71,
            quote: 'Some people are immune to good advice.',
            char_id: 8
        },
        {
            quote_id: 72,
            quote: 'You either run from things, or you face them, Mr. White.',
            char_id: 2
        },
        {
            quote_id: 73,
            quote: 'You add a plus douce bag to a minus douche bag and you get, like, zero douche bags.',
            char_id: 2
        },
        { quote_id: 74, quote: 'Yeah, totally Kafkaesque.', char_id: 2 },
        {
            quote_id: 75,
            quote: 'Hey, you girls. Want to meet my fat stack?',
            char_id: 2
        },
        {
            quote_id: 76,
            quote: 'Everyone sounds like Meryl Streep with a gun to their head.',
            char_id: 7
        },
        {
            quote_id: 77,
            quote: 'The next time you bring a gun to a job without telling me, I will stick it up your ass sideways.',
            char_id: 7
        },
        {
            quote_id: 78,
            quote: "You know how they say, 'It's been a pleasure?' It hasn't.",
            char_id: 7
        },
        {
            quote_id: 79,
            quote: "Big doings today. The order of the day is 'eyes open, mouth shut.'",
            char_id: 7
        },
        {
            quote_id: 80,
            quote: "You're an insane, degenerate piece of filth, and you deserve to die.",
            char_id: 1
        },
        { quote_id: 81, quote: 'You two suck at peddling meth.', char_id: 8 },
        {
            quote_id: 82,
            quote: 'Mas his death satisfy you.',
            char_id: 9
        },
        { quote_id: 83, quote: 'La familia es todo.', char_id: 10 },
        {
            quote_id: 84,
            quote: 'I will kill your wife, I will kill your son, I will kill your infant daughter.',
            char_id: 9
        },
        {
            quote_id: 85,
            quote: 'It’s discreet, like a stripper pole in a mosque.',
            char_id: 8
        },
        { quote_id: 86, quote: "I'm a lawyer, not a criminal", char_id: 8 },
        {
            quote_id: 87,
            quote: 'Only two things I know about Albuquerque – Bugs Bunny should’ve taken a left turn there. And give me a hundred tries, I’ll never be able spell it.',
            char_id: 8
        },
        {
            quote_id: 88,
            quote: 'I am not good at Building Shit , you know I’m excellent at Tearing it down',
            char_id: 8
        },
        {
            quote_id: 89,
            quote: 'I know what stopped me. And you know what? It’s never stopping me again.',
            char_id: 8
        },
        {
            quote_id: 90,
            quote: 'Perfection is the Enemy of Perfectly Adequate',
            char_id: 8
        },
        {
            quote_id: 91,
            quote: 'Hail Satan. I submit to the dark side.',
            char_id: 8
        },
        {
            quote_id: 92,
            quote: 'There’s no honor among thieves… except for us of course',
            char_id: 8
        },
        {
            quote_id: 93,
            quote: 'Some people are immune to good advice.',
            char_id: 8
        },
        { quote_id: 94, quote: 'Money is the Point.', char_id: 8 },
        {
            quote_id: 95,
            quote: 'You Know the expression it’s been a pleasure... well it hasn’t.',
            char_id: 7
        },
        {
            quote_id: 96,
            quote: 'Winning Doesn’t Always Mean Getting a Favorable Verdict at Trial.',
            char_id: 112
        },
        {
            quote_id: 97,
            quote: 'You know what happened. The question is, can you live with it?',
            char_id: 7
        },
        {
            quote_id: 98,
            quote: 'Slippin’ Jimmy with a law degree is like a chimp with a machine gun',
            char_id: 114
        },
        {
            quote_id: 99,
            quote: 'No one ever accused you of being lazy.. every other sin in the book , but not that one.',
            char_id: 114
        },
        { quote_id: 100, quote: 'FYI, old people adore me.', char_id: 8 },
        {
            quote_id: 101,
            quote: "I'm gonna be a damn good lawyer, and people are gonna know about it",
            char_id: 8
        },
        { quote_id: 102, quote: "S'all good, man.", char_id: 8 }
    ],
    episodes: [
        { episode_id: 1, title: 'Pilot', season: '1', episode: '1' },
        {
            episode_id: 2,
            title: "Cat's in the Bag...",
            season: '1',
            episode: '2'
        },
        {
            episode_id: 3,
            title: "...And the Bag's in the River",
            season: '1',
            episode: '3'
        },
        { episode_id: 4, title: 'Cancer Man', season: '1', episode: '4' },
        { episode_id: 5, title: 'Gray Matter', season: '1', episode: '5' },
        {
            episode_id: 6,
            title: 'Crazy Handful of Nothin',
            season: '1',
            episode: '6'
        },
        {
            episode_id: 7,
            title: 'A No-Rough-Stuff-Type Deal',
            season: ' 1',
            episode: '7'
        },
        {
            episode_id: 8,
            title: 'Seven-Thirty-Seven',
            season: '2',
            episode: '1'
        },
        { episode_id: 9, title: 'Grilled', season: '2', episode: '2' },
        {
            episode_id: 10,
            title: 'Bit by a Dead Bee',
            season: '2',
            episode: '3'
        },
        { episode_id: 11, title: 'Down', season: '2', episode: '4' },
        { episode_id: 12, title: 'Breakage', season: '2', episode: '5' },
        { episode_id: 13, title: 'Peekaboo', season: '2', episode: '6' },
        { episode_id: 14, title: 'Negro y Azul', season: '2', episode: '7' },
        {
            episode_id: 15,
            title: 'Better Call Saul',
            season: '2',
            episode: '8'
        },
        { episode_id: 16, title: '4 Days Out', season: '2', episode: '9' },
        { episode_id: 17, title: 'Over', season: '2', episode: '10' },
        { episode_id: 18, title: 'Mandala', season: '2', episode: '11' },
        { episode_id: 19, title: 'Phoenix', season: '2', episode: '12' },
        { episode_id: 20, title: 'ABQ', season: '2', episode: '13' },
        { episode_id: 21, title: 'No Más', season: '3', episode: '1' },
        {
            episode_id: 22,
            title: 'Caballo sin Nombre',
            season: '3',
            episode: '2'
        },
        { episode_id: 23, title: 'IFT', season: '3', episode: '3' },
        { episode_id: 24, title: 'Green Light', season: '3', episode: '4' },
        { episode_id: 25, title: 'Más', season: '3', episode: '5' },
        { episode_id: 26, title: 'Sunset', season: '3', episode: '6' },
        { episode_id: 27, title: 'One Minute', season: '3', episode: '7' },
        { episode_id: 28, title: 'I See You', season: '3', episode: '8' },
        { episode_id: 29, title: 'Kafkaesque', season: '3', episode: '9' },
        { episode_id: 30, title: 'Fly', season: '3', episode: '10' },
        { episode_id: 31, title: 'Abiquiu', season: '3', episode: '11' },
        {
            episode_id: 32,
            title: 'Half measures',
            season: '3',
            episode: '12'
        },
        { episode_id: 33, title: 'Full Measure', season: '3', episode: '13' },
        { episode_id: 34, title: 'Box Cutter', season: '4', episode: '1' },
        {
            episode_id: 35,
            title: 'Thirty-Eight Snub',
            season: '4',
            episode: '2'
        },
        { episode_id: 36, title: 'Open House', season: '4', episode: '3' },
        { episode_id: 37, title: 'Bullet Points', season: '4', episode: '4' },
        { episode_id: 38, title: 'Shotgun', season: '4', episode: '5' },
        { episode_id: 39, title: 'Cornered', season: '4', episode: '6' },
        { episode_id: 40, title: 'Problem Dog', season: '4', episode: '7' },
        { episode_id: 41, title: 'Hermanos', season: '4', episode: '8' },
        { episode_id: 42, title: 'Bug', season: '4', episode: '9' },
        { episode_id: 43, title: 'Salud', season: '4', episode: '10' },
        { episode_id: 44, title: 'Crawl Space', season: '4', episode: '11' },
        { episode_id: 45, title: 'End Times', season: '4', episode: '12' },
        { episode_id: 46, title: 'Face Off', season: '4', episode: '13' },
        {
            episode_id: 47,
            title: 'Live Free of Die',
            season: '5',
            episode: '1'
        },
        { episode_id: 48, title: 'Madrigal', season: '5', episode: '2' },
        { episode_id: 49, title: 'Hazard Pay', season: '5', episode: '3' },
        { episode_id: 50, title: 'Fifty-One', season: '5', episode: '4' },
        { episode_id: 51, title: 'Dead Freight', season: '5', episode: '5' },
        { episode_id: 52, title: 'Buyout', season: '5', episode: '6' },
        { episode_id: 53, title: 'Say My Name', season: '5', episode: '7' },
        {
            episode_id: 54,
            title: 'Gliding Over All',
            season: '5',
            episode: '8'
        },
        { episode_id: 55, title: 'Blood Money', season: '5', episode: '9' },
        { episode_id: 56, title: 'Buried', season: '5', episode: '10' },
        { episode_id: 57, title: 'Confessions', season: '5', episode: '11' },
        { episode_id: 58, title: 'Rabid Dog', season: '5', episode: '12' },
        { episode_id: 59, title: "To'hajilee", season: '5', episode: '13' },
        { episode_id: 60, title: 'Ozymandias', season: '5', episode: '14' },
        {
            episode_id: 61,
            title: 'Granite State',
            season: '5',
            episode: '15'
        },
        { episode_id: 62, title: 'Felina', season: '5', episode: '16' }
    ],
    characters_episodes: [
        { episode_id: 1, char_id: 1 },
        { episode_id: 1, char_id: 2 },
        { episode_id: 1, char_id: 3 },
        { episode_id: 1, char_id: 5 },
        { episode_id: 1, char_id: 6 },
        { episode_id: 1, char_id: 4 },
        { episode_id: 1, char_id: 11 },
        { episode_id: 1, char_id: 37 },
        { episode_id: 2, char_id: 1 },
        { episode_id: 2, char_id: 2 },
        { episode_id: 2, char_id: 3 },
        { episode_id: 2, char_id: 4 },
        { episode_id: 2, char_id: 11 },
        { episode_id: 3, char_id: 1 },
        { episode_id: 3, char_id: 2 },
        { episode_id: 3, char_id: 3 },
        { episode_id: 3, char_id: 5 },
        { episode_id: 3, char_id: 6 },
        { episode_id: 3, char_id: 4 },
        { episode_id: 3, char_id: 11 },
        { episode_id: 3, char_id: 26 },
        { episode_id: 4, char_id: 1 },
        { episode_id: 4, char_id: 2 },
        { episode_id: 4, char_id: 3 },
        { episode_id: 4, char_id: 5 },
        { episode_id: 4, char_id: 6 },
        { episode_id: 4, char_id: 4 },
        { episode_id: 4, char_id: 38 },
        { episode_id: 5, char_id: 1 },
        { episode_id: 5, char_id: 2 },
        { episode_id: 5, char_id: 3 },
        { episode_id: 5, char_id: 5 },
        { episode_id: 5, char_id: 6 },
        { episode_id: 5, char_id: 4 },
        { episode_id: 5, char_id: 27 },
        { episode_id: 5, char_id: 26 },
        { episode_id: 5, char_id: 18 },
        { episode_id: 6, char_id: 1 },
        { episode_id: 6, char_id: 2 },
        { episode_id: 6, char_id: 3 },
        { episode_id: 6, char_id: 5 },
        { episode_id: 6, char_id: 6 },
        { episode_id: 6, char_id: 4 },
        { episode_id: 6, char_id: 12 },
        { episode_id: 7, char_id: 1 },
        { episode_id: 7, char_id: 2 },
        { episode_id: 7, char_id: 3 },
        { episode_id: 7, char_id: 5 },
        { episode_id: 7, char_id: 6 },
        { episode_id: 7, char_id: 4 },
        { episode_id: 7, char_id: 12 },
        { episode_id: 8, char_id: 1 },
        { episode_id: 8, char_id: 2 },
        { episode_id: 8, char_id: 3 },
        { episode_id: 8, char_id: 5 },
        { episode_id: 8, char_id: 6 },
        { episode_id: 8, char_id: 4 },
        { episode_id: 8, char_id: 12 },
        { episode_id: 9, char_id: 1 },
        { episode_id: 9, char_id: 2 },
        { episode_id: 9, char_id: 3 },
        { episode_id: 9, char_id: 5 },
        { episode_id: 9, char_id: 6 },
        { episode_id: 9, char_id: 4 },
        { episode_id: 9, char_id: 12 },
        { episode_id: 9, char_id: 10 },
        { episode_id: 10, char_id: 1 },
        { episode_id: 10, char_id: 2 },
        { episode_id: 10, char_id: 3 },
        { episode_id: 10, char_id: 5 },
        { episode_id: 10, char_id: 6 },
        { episode_id: 10, char_id: 4 },
        { episode_id: 10, char_id: 10 },
        { episode_id: 11, char_id: 1 },
        { episode_id: 11, char_id: 2 },
        { episode_id: 11, char_id: 3 },
        { episode_id: 11, char_id: 4 },
        { episode_id: 12, char_id: 1 },
        { episode_id: 12, char_id: 2 },
        { episode_id: 12, char_id: 3 },
        { episode_id: 12, char_id: 5 },
        { episode_id: 12, char_id: 6 },
        { episode_id: 12, char_id: 4 },
        { episode_id: 12, char_id: 16 },
        { episode_id: 12, char_id: 18 },
        { episode_id: 13, char_id: 1 },
        { episode_id: 13, char_id: 2 },
        { episode_id: 13, char_id: 3 },
        { episode_id: 13, char_id: 6 },
        { episode_id: 13, char_id: 4 },
        { episode_id: 13, char_id: 26 },
        { episode_id: 14, char_id: 1 },
        { episode_id: 14, char_id: 2 },
        { episode_id: 14, char_id: 3 },
        { episode_id: 14, char_id: 5 },
        { episode_id: 14, char_id: 6 },
        { episode_id: 14, char_id: 4 },
        { episode_id: 14, char_id: 48 },
        { episode_id: 14, char_id: 16 },
        { episode_id: 14, char_id: 21 },
        { episode_id: 15, char_id: 1 },
        { episode_id: 15, char_id: 2 },
        { episode_id: 15, char_id: 3 },
        { episode_id: 15, char_id: 5 },
        { episode_id: 15, char_id: 6 },
        { episode_id: 15, char_id: 8 },
        { episode_id: 15, char_id: 16 },
        { episode_id: 15, char_id: 18 },
        { episode_id: 16, char_id: 1 },
        { episode_id: 16, char_id: 2 },
        { episode_id: 16, char_id: 3 },
        { episode_id: 16, char_id: 5 },
        { episode_id: 16, char_id: 6 },
        { episode_id: 16, char_id: 4 },
        { episode_id: 16, char_id: 8 },
        { episode_id: 16, char_id: 16 },
        { episode_id: 17, char_id: 1 },
        { episode_id: 17, char_id: 2 },
        { episode_id: 17, char_id: 3 },
        { episode_id: 17, char_id: 5 },
        { episode_id: 17, char_id: 6 },
        { episode_id: 17, char_id: 4 },
        { episode_id: 17, char_id: 16 },
        { episode_id: 17, char_id: 21 },
        { episode_id: 18, char_id: 1 },
        { episode_id: 18, char_id: 2 },
        { episode_id: 18, char_id: 3 },
        { episode_id: 18, char_id: 8 },
        { episode_id: 18, char_id: 9 },
        { episode_id: 18, char_id: 16 },
        { episode_id: 18, char_id: 21 },
        { episode_id: 18, char_id: 41 },
        { episode_id: 18, char_id: 29 },
        { episode_id: 19, char_id: 1 },
        { episode_id: 19, char_id: 2 },
        { episode_id: 19, char_id: 3 },
        { episode_id: 19, char_id: 5 },
        { episode_id: 19, char_id: 6 },
        { episode_id: 19, char_id: 4 },
        { episode_id: 19, char_id: 8 },
        { episode_id: 19, char_id: 16 },
        { episode_id: 19, char_id: 21 },
        { episode_id: 19, char_id: 41 },
        { episode_id: 20, char_id: 1 },
        { episode_id: 20, char_id: 2 },
        { episode_id: 20, char_id: 3 },
        { episode_id: 20, char_id: 5 },
        { episode_id: 20, char_id: 6 },
        { episode_id: 20, char_id: 4 },
        { episode_id: 20, char_id: 7 },
        { episode_id: 20, char_id: 9 },
        { episode_id: 20, char_id: 16 },
        { episode_id: 20, char_id: 41 },
        { episode_id: 21, char_id: 1 },
        { episode_id: 21, char_id: 2 },
        { episode_id: 21, char_id: 3 },
        { episode_id: 21, char_id: 5 },
        { episode_id: 21, char_id: 6 },
        { episode_id: 21, char_id: 4 },
        { episode_id: 21, char_id: 9 },
        { episode_id: 21, char_id: 13 },
        { episode_id: 22, char_id: 1 },
        { episode_id: 22, char_id: 2 },
        { episode_id: 22, char_id: 3 },
        { episode_id: 22, char_id: 5 },
        { episode_id: 22, char_id: 6 },
        { episode_id: 22, char_id: 4 },
        { episode_id: 22, char_id: 9 },
        { episode_id: 22, char_id: 8 },
        { episode_id: 22, char_id: 7 },
        { episode_id: 22, char_id: 10 },
        { episode_id: 23, char_id: 1 },
        { episode_id: 23, char_id: 2 },
        { episode_id: 23, char_id: 3 },
        { episode_id: 23, char_id: 5 },
        { episode_id: 23, char_id: 4 },
        { episode_id: 23, char_id: 9 },
        { episode_id: 23, char_id: 8 },
        { episode_id: 23, char_id: 10 },
        { episode_id: 23, char_id: 21 },
        { episode_id: 24, char_id: 1 },
        { episode_id: 24, char_id: 2 },
        { episode_id: 24, char_id: 3 },
        { episode_id: 24, char_id: 5 },
        { episode_id: 24, char_id: 6 },
        { episode_id: 24, char_id: 4 },
        { episode_id: 24, char_id: 9 },
        { episode_id: 24, char_id: 8 },
        { episode_id: 24, char_id: 7 },
        { episode_id: 24, char_id: 21 },
        { episode_id: 25, char_id: 1 },
        { episode_id: 25, char_id: 2 },
        { episode_id: 25, char_id: 3 },
        { episode_id: 25, char_id: 5 },
        { episode_id: 25, char_id: 6 },
        { episode_id: 25, char_id: 4 },
        { episode_id: 25, char_id: 9 },
        { episode_id: 25, char_id: 8 },
        { episode_id: 25, char_id: 21 },
        { episode_id: 26, char_id: 1 },
        { episode_id: 26, char_id: 2 },
        { episode_id: 26, char_id: 3 },
        { episode_id: 26, char_id: 5 },
        { episode_id: 26, char_id: 6 },
        { episode_id: 26, char_id: 4 },
        { episode_id: 26, char_id: 9 },
        { episode_id: 26, char_id: 8 },
        { episode_id: 26, char_id: 22 },
        { episode_id: 26, char_id: 13 },
        { episode_id: 27, char_id: 1 },
        { episode_id: 27, char_id: 2 },
        { episode_id: 27, char_id: 3 },
        { episode_id: 27, char_id: 5 },
        { episode_id: 27, char_id: 6 },
        { episode_id: 27, char_id: 8 },
        { episode_id: 27, char_id: 10 },
        { episode_id: 27, char_id: 13 },
        { episode_id: 27, char_id: 22 },
        { episode_id: 28, char_id: 1 },
        { episode_id: 28, char_id: 2 },
        { episode_id: 28, char_id: 3 },
        { episode_id: 28, char_id: 5 },
        { episode_id: 28, char_id: 6 },
        { episode_id: 28, char_id: 4 },
        { episode_id: 28, char_id: 9 },
        { episode_id: 28, char_id: 7 },
        { episode_id: 29, char_id: 1 },
        { episode_id: 29, char_id: 2 },
        { episode_id: 29, char_id: 3 },
        { episode_id: 29, char_id: 5 },
        { episode_id: 29, char_id: 6 },
        { episode_id: 29, char_id: 4 },
        { episode_id: 29, char_id: 9 },
        { episode_id: 29, char_id: 8 },
        { episode_id: 29, char_id: 21 },
        { episode_id: 30, char_id: 1 },
        { episode_id: 30, char_id: 2 },
        { episode_id: 31, char_id: 1 },
        { episode_id: 31, char_id: 2 },
        { episode_id: 31, char_id: 3 },
        { episode_id: 31, char_id: 5 },
        { episode_id: 31, char_id: 6 },
        { episode_id: 31, char_id: 4 },
        { episode_id: 31, char_id: 9 },
        { episode_id: 31, char_id: 8 },
        { episode_id: 31, char_id: 16 },
        { episode_id: 32, char_id: 1 },
        { episode_id: 32, char_id: 2 },
        { episode_id: 32, char_id: 3 },
        { episode_id: 32, char_id: 5 },
        { episode_id: 32, char_id: 6 },
        { episode_id: 32, char_id: 4 },
        { episode_id: 32, char_id: 9 },
        { episode_id: 32, char_id: 8 },
        { episode_id: 32, char_id: 7 },
        { episode_id: 32, char_id: 23 },
        { episode_id: 32, char_id: 44 },
        { episode_id: 33, char_id: 1 },
        { episode_id: 33, char_id: 2 },
        { episode_id: 33, char_id: 3 },
        { episode_id: 33, char_id: 4 },
        { episode_id: 33, char_id: 9 },
        { episode_id: 33, char_id: 8 },
        { episode_id: 33, char_id: 7 },
        { episode_id: 33, char_id: 22 },
        { episode_id: 33, char_id: 44 },
        { episode_id: 34, char_id: 1 },
        { episode_id: 34, char_id: 2 },
        { episode_id: 34, char_id: 3 },
        { episode_id: 34, char_id: 5 },
        { episode_id: 34, char_id: 6 },
        { episode_id: 34, char_id: 4 },
        { episode_id: 34, char_id: 9 },
        { episode_id: 34, char_id: 8 },
        { episode_id: 34, char_id: 7 },
        { episode_id: 34, char_id: 22 },
        { episode_id: 34, char_id: 44 },
        { episode_id: 35, char_id: 1 },
        { episode_id: 35, char_id: 2 },
        { episode_id: 35, char_id: 3 },
        { episode_id: 35, char_id: 5 },
        { episode_id: 35, char_id: 6 },
        { episode_id: 35, char_id: 4 },
        { episode_id: 35, char_id: 9 },
        { episode_id: 35, char_id: 8 },
        { episode_id: 35, char_id: 7 },
        { episode_id: 35, char_id: 23 },
        { episode_id: 36, char_id: 1 },
        { episode_id: 36, char_id: 2 },
        { episode_id: 36, char_id: 3 },
        { episode_id: 36, char_id: 5 },
        { episode_id: 36, char_id: 6 },
        { episode_id: 36, char_id: 8 },
        { episode_id: 36, char_id: 37 },
        { episode_id: 37, char_id: 1 },
        { episode_id: 37, char_id: 2 },
        { episode_id: 37, char_id: 3 },
        { episode_id: 37, char_id: 5 },
        { episode_id: 37, char_id: 6 },
        { episode_id: 37, char_id: 4 },
        { episode_id: 37, char_id: 9 },
        { episode_id: 37, char_id: 8 },
        { episode_id: 37, char_id: 7 },
        { episode_id: 37, char_id: 22 },
        { episode_id: 38, char_id: 1 },
        { episode_id: 38, char_id: 2 },
        { episode_id: 38, char_id: 3 },
        { episode_id: 38, char_id: 5 },
        { episode_id: 38, char_id: 6 },
        { episode_id: 38, char_id: 4 },
        { episode_id: 38, char_id: 9 },
        { episode_id: 38, char_id: 7 },
        { episode_id: 39, char_id: 1 },
        { episode_id: 39, char_id: 2 },
        { episode_id: 39, char_id: 3 },
        { episode_id: 39, char_id: 4 },
        { episode_id: 39, char_id: 9 },
        { episode_id: 39, char_id: 7 },
        { episode_id: 39, char_id: 37 },
        { episode_id: 40, char_id: 1 },
        { episode_id: 40, char_id: 2 },
        { episode_id: 40, char_id: 3 },
        { episode_id: 40, char_id: 5 },
        { episode_id: 40, char_id: 6 },
        { episode_id: 40, char_id: 4 },
        { episode_id: 40, char_id: 9 },
        { episode_id: 40, char_id: 8 },
        { episode_id: 40, char_id: 7 },
        { episode_id: 40, char_id: 22 },
        { episode_id: 41, char_id: 1 },
        { episode_id: 41, char_id: 2 },
        { episode_id: 41, char_id: 3 },
        { episode_id: 41, char_id: 5 },
        { episode_id: 41, char_id: 6 },
        { episode_id: 41, char_id: 4 },
        { episode_id: 41, char_id: 9 },
        { episode_id: 41, char_id: 8 },
        { episode_id: 41, char_id: 7 },
        { episode_id: 41, char_id: 10 },
        { episode_id: 41, char_id: 23 },
        { episode_id: 42, char_id: 1 },
        { episode_id: 42, char_id: 2 },
        { episode_id: 42, char_id: 3 },
        { episode_id: 42, char_id: 5 },
        { episode_id: 42, char_id: 6 },
        { episode_id: 42, char_id: 9 },
        { episode_id: 42, char_id: 7 },
        { episode_id: 42, char_id: 21 },
        { episode_id: 43, char_id: 1 },
        { episode_id: 43, char_id: 2 },
        { episode_id: 43, char_id: 3 },
        { episode_id: 43, char_id: 4 },
        { episode_id: 43, char_id: 9 },
        { episode_id: 43, char_id: 8 },
        { episode_id: 43, char_id: 7 },
        { episode_id: 43, char_id: 21 },
        { episode_id: 44, char_id: 1 },
        { episode_id: 44, char_id: 2 },
        { episode_id: 44, char_id: 3 },
        { episode_id: 44, char_id: 5 },
        { episode_id: 44, char_id: 6 },
        { episode_id: 44, char_id: 4 },
        { episode_id: 44, char_id: 9 },
        { episode_id: 44, char_id: 8 },
        { episode_id: 44, char_id: 7 },
        { episode_id: 44, char_id: 10 },
        { episode_id: 44, char_id: 21 },
        { episode_id: 44, char_id: 23 },
        { episode_id: 45, char_id: 1 },
        { episode_id: 45, char_id: 2 },
        { episode_id: 45, char_id: 3 },
        { episode_id: 45, char_id: 5 },
        { episode_id: 45, char_id: 6 },
        { episode_id: 45, char_id: 4 },
        { episode_id: 45, char_id: 9 },
        { episode_id: 45, char_id: 8 },
        { episode_id: 45, char_id: 23 },
        { episode_id: 46, char_id: 1 },
        { episode_id: 46, char_id: 2 },
        { episode_id: 46, char_id: 3 },
        { episode_id: 46, char_id: 5 },
        { episode_id: 46, char_id: 6 },
        { episode_id: 46, char_id: 4 },
        { episode_id: 46, char_id: 9 },
        { episode_id: 46, char_id: 8 },
        { episode_id: 47, char_id: 1 },
        { episode_id: 47, char_id: 2 },
        { episode_id: 47, char_id: 3 },
        { episode_id: 47, char_id: 5 },
        { episode_id: 47, char_id: 4 },
        { episode_id: 47, char_id: 8 },
        { episode_id: 47, char_id: 7 },
        { episode_id: 47, char_id: 21 },
        { episode_id: 48, char_id: 1 },
        { episode_id: 48, char_id: 2 },
        { episode_id: 48, char_id: 3 },
        { episode_id: 48, char_id: 5 },
        { episode_id: 48, char_id: 4 },
        { episode_id: 48, char_id: 8 },
        { episode_id: 48, char_id: 7 },
        { episode_id: 48, char_id: 14 },
        { episode_id: 49, char_id: 1 },
        { episode_id: 49, char_id: 2 },
        { episode_id: 49, char_id: 3 },
        { episode_id: 49, char_id: 6 },
        { episode_id: 49, char_id: 4 },
        { episode_id: 49, char_id: 8 },
        { episode_id: 49, char_id: 7 },
        { episode_id: 49, char_id: 18 },
        { episode_id: 49, char_id: 23 },
        { episode_id: 49, char_id: 15 },
        { episode_id: 50, char_id: 1 },
        { episode_id: 50, char_id: 2 },
        { episode_id: 50, char_id: 3 },
        { episode_id: 50, char_id: 5 },
        { episode_id: 50, char_id: 6 },
        { episode_id: 50, char_id: 4 },
        { episode_id: 50, char_id: 7 },
        { episode_id: 50, char_id: 14 },
        { episode_id: 51, char_id: 1 },
        { episode_id: 51, char_id: 2 },
        { episode_id: 51, char_id: 3 },
        { episode_id: 51, char_id: 5 },
        { episode_id: 51, char_id: 6 },
        { episode_id: 51, char_id: 4 },
        { episode_id: 51, char_id: 7 },
        { episode_id: 51, char_id: 14 },
        { episode_id: 51, char_id: 15 },
        { episode_id: 52, char_id: 1 },
        { episode_id: 52, char_id: 2 },
        { episode_id: 52, char_id: 3 },
        { episode_id: 52, char_id: 5 },
        { episode_id: 52, char_id: 6 },
        { episode_id: 52, char_id: 8 },
        { episode_id: 52, char_id: 7 },
        { episode_id: 52, char_id: 15 },
        { episode_id: 53, char_id: 1 },
        { episode_id: 53, char_id: 2 },
        { episode_id: 53, char_id: 3 },
        { episode_id: 53, char_id: 5 },
        { episode_id: 53, char_id: 8 },
        { episode_id: 53, char_id: 7 },
        { episode_id: 53, char_id: 15 },
        { episode_id: 54, char_id: 1 },
        { episode_id: 54, char_id: 2 },
        { episode_id: 54, char_id: 3 },
        { episode_id: 54, char_id: 5 },
        { episode_id: 54, char_id: 6 },
        { episode_id: 54, char_id: 4 },
        { episode_id: 54, char_id: 8 },
        { episode_id: 54, char_id: 7 },
        { episode_id: 54, char_id: 14 },
        { episode_id: 54, char_id: 15 },
        { episode_id: 55, char_id: 1 },
        { episode_id: 55, char_id: 2 },
        { episode_id: 55, char_id: 3 },
        { episode_id: 55, char_id: 5 },
        { episode_id: 55, char_id: 6 },
        { episode_id: 55, char_id: 4 },
        { episode_id: 55, char_id: 8 },
        { episode_id: 55, char_id: 14 },
        { episode_id: 55, char_id: 18 },
        { episode_id: 55, char_id: 17 },
        { episode_id: 56, char_id: 1 },
        { episode_id: 56, char_id: 2 },
        { episode_id: 56, char_id: 3 },
        { episode_id: 56, char_id: 5 },
        { episode_id: 56, char_id: 6 },
        { episode_id: 56, char_id: 8 },
        { episode_id: 56, char_id: 14 },
        { episode_id: 56, char_id: 15 },
        { episode_id: 56, char_id: 57 },
        { episode_id: 57, char_id: 1 },
        { episode_id: 57, char_id: 2 },
        { episode_id: 57, char_id: 3 },
        { episode_id: 57, char_id: 5 },
        { episode_id: 57, char_id: 6 },
        { episode_id: 57, char_id: 4 },
        { episode_id: 57, char_id: 8 },
        { episode_id: 57, char_id: 15 },
        { episode_id: 57, char_id: 57 },
        { episode_id: 58, char_id: 1 },
        { episode_id: 58, char_id: 2 },
        { episode_id: 58, char_id: 3 },
        { episode_id: 58, char_id: 5 },
        { episode_id: 58, char_id: 6 },
        { episode_id: 58, char_id: 4 },
        { episode_id: 58, char_id: 8 },
        { episode_id: 59, char_id: 1 },
        { episode_id: 59, char_id: 2 },
        { episode_id: 59, char_id: 3 },
        { episode_id: 59, char_id: 5 },
        { episode_id: 59, char_id: 6 },
        { episode_id: 59, char_id: 4 },
        { episode_id: 59, char_id: 8 },
        { episode_id: 59, char_id: 14 },
        { episode_id: 59, char_id: 15 },
        { episode_id: 59, char_id: 23 },
        { episode_id: 59, char_id: 57 },
        { episode_id: 60, char_id: 1 },
        { episode_id: 60, char_id: 2 },
        { episode_id: 60, char_id: 3 },
        { episode_id: 60, char_id: 5 },
        { episode_id: 60, char_id: 6 },
        { episode_id: 60, char_id: 4 },
        { episode_id: 60, char_id: 15 },
        { episode_id: 60, char_id: 57 },
        { episode_id: 60, char_id: 20 },
        { episode_id: 61, char_id: 1 },
        { episode_id: 61, char_id: 2 },
        { episode_id: 61, char_id: 3 },
        { episode_id: 61, char_id: 6 },
        { episode_id: 61, char_id: 8 },
        { episode_id: 61, char_id: 14 },
        { episode_id: 61, char_id: 15 },
        { episode_id: 61, char_id: 57 },
        { episode_id: 61, char_id: 23 },
        { episode_id: 61, char_id: 27 },
        { episode_id: 61, char_id: 26 },
        { episode_id: 62, char_id: 1 },
        { episode_id: 62, char_id: 2 },
        { episode_id: 62, char_id: 3 },
        { episode_id: 62, char_id: 6 },
        { episode_id: 62, char_id: 4 },
        { episode_id: 62, char_id: 14 },
        { episode_id: 62, char_id: 15 },
        { episode_id: 62, char_id: 57 },
        { episode_id: 62, char_id: 18 },
        { episode_id: 62, char_id: 17 },
        { episode_id: 62, char_id: 27 },
        { episode_id: 62, char_id: 26 }
    ]
};
